export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const SET_LOADING = "SET_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_COURSE_TO_USER_SUCCESS = "ADD_COURSE_TO_USER_SUCCESS";
export const ADD_COURSE_TO_USER_FAIL = "ADD_COURSE_TO_USER_FAIL";

export const SET_WATCHED_SUCCESS = "SET_WATCHED_SUCCESS";
export const SET_WATCHED_FAIL = "SET_WATCHED_FAIL";
